version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - restore_cache:
          name: restore yarn package cache
          keys: 
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: installing dependencies
          command: yarn
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - deploy:
          name: deploying build
          command: |
            git config --global user.name $GH_NAME
            git config --global user.email $GH_EMAIL
            git clone $CIRCLE_REPOSITORY_URL
            cd core
            yarn
            yarn build
            gh-pages -m "automated deploy: ${CIRCLE_SHA1}" -d build
