version: 2
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8
    environment:
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - run:
          name: installing dependencies
          command: yarn install --frozen-lockfile
      - deploy:
          name: deploying build
          command: ./.circleci/deploy.sh
      - save_cache:
          name: save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          name: restore yarn package cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
